### ISSUE TITLE
Actividad 2

### ISSUE THREAD

**Issue by ROJASMA** [Taller-Abierto-de-Humanidades-Digitales/curso_python#23]
https://colab.research.google.com/drive/1Y7AOLoGUzRKoXM2lbrN31_zo52lIniE_?usp=sharing

**Comment by jairomelo** [comment]
Guíate de mi cuaderno para que puedas completar el ejercicio 😉

https://colab.research.google.com/drive/1cabSogOA30FKx8fA3LNMK5SuERGS21mz?usp=sharing
