### ISSUE TITLE
Actividad programa real 

### ISSUE THREAD

**Issue by Denissedjg** [Taller-Abierto-de-Humanidades-Digitales/curso_python#28]
El enlace de tu cuaderno:
https://colab.research.google.com/drive/1gpgPKBlfGAJHQfTNP4DmlEZm2Iu8MKGs?usp=sharing

**Comment by jairomelo** [comment]
Hola @Denissedjg ,
Ya encontré el error :)

En el ejercicio 4, faltaba hacer el llamado a la función `extraer_fechas()`:

```
def fecha_defuncion(autor, biografias_boom): # pasa dos parámetros
    """Completa la función para que devuelva la fecha de defunción del autor"""
    autor_dict = biografias_boom[autor]
    if autor_dict["vivo"]:
        return "El autor está vivo"
    else:
        fechas = extraer_fechas(autor_dict["bio"]) # <-- Aquí estaba el error :)
        return max(fechas)
```

Al corregir ese error todo el resto del programa funciona correctamente 😃

**Comment by jairomelo** [comment]
No te disculpes @Denissedjg . Al contrario, muchas gracias por preguntar 🙇🏼
