### ISSUE TITLE
Actividad aspectos básicos Ariadna H.

### ISSUE THREAD

**Issue by AriadnaHerndez** [Taller-Abierto-de-Humanidades-Digitales/curso_python#6]
El enlace de tu cuaderno: https://colab.research.google.com/drive/1p6D2kgcEYKClp-u5vjRLR8lQ6ST2T8ZR?usp=sharing

**Comment by jairomelo** [comment]
Hola @AriadnaHerndez 
Ya encontré los errores en la actividad 8:

```
autores_boom = {
    "Juan Rulfo": {
        "nacionalidad": "mexicana",
        "obra": "Pedro Páramo",
        "año": 1955
    },
    "Ernesto Sábato": {
        "nacionalidad": "argentina",
        "obra": "El túnel",
        "año": 1962,
    },
    "Gabriel García Márquez": {
        "nacionalidad": "colombiana",
        "obra": "Cien años de soledad",
        "año": 1967
    },
    "Mario Vargas Llosa": {
        "nacionalidad": "peruana",
        "año": 1962
    },
    "Julio Cortázar": {
        "nacionalidad": "argentina",
        "obra": "Rayuela",
        "año": 1963
    },
} # <-- Habías eliminado esta llave
autores_boom["Mario Vargas Llosa"]['obra']="La ciudad y los perros" # Estaba mal escrito (MarioVargas en lugar de Mario Vargas)
print(autores_boom)
```

La actividad 9 se debería ejecutar bien, **pero** tienes que cambiar el valor de la fecha por uno numérico (es decir, sin comillas)

Realiza esas modificaciones y todo funcionará perfecto :)

**Comment by AriadnaHerndez** [comment]
Muchas gracias Jairo,

ya lo corregí y funciona a la perfección.

Nos vemos el miércoles,

Ariadna Hernández :)

Gracias de antemano,

Ariadna Hernández
________________________________
